spring.application.name=documentModification2_0
spring.thymeleaf.encoding=UTF-8



logging.level.org.jodconverter.local.office.VerboseProcess=OFF


spring.datasource.url=jdbc:h2:mem:docdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.h2.console.enabled=false
spring.h2.console.path=/h2-console
#spring.datasource.username= postgres
#spring.datasource.password= postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/document_statistic_db





spring.liquibase.change-log=db/changelog/changeLog.xml
spring.liquibase.enabled=false