spring.application.name=documentModification2_0
spring.thymeleaf.encoding=UTF-8
logging.level.org.jodconverter.local.office.VerboseProcess=OFF

spring.datasource.username= postgres
spring.datasource.password= postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/document_statistic_db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name


spring.liquibase.change-log=db/changelog/changeLog.xml
spring.liquibase.enabled=true